[book]
title = "KSL Documentation"
authors = ["kgsensei"]
description = "KSL Programming Language Documentation"
language = "en"
src = "src"

[build]
build-dir = "bin/docs"

[output.html]
git-repository-url = "https://github.com/kslng/ksl"
preferred-dark-theme = "navy"
sidebar-header-nav = true
default-theme = "navy"
site-url = "/docs/"

[output.html.search]
limit-results = 15
