[book]
title = "KSL Documentation"
authors = ["kgsensei"]
description = "KSL Programming Language Documentation"
language = "en"
src = "src"

[build]
build-dir = "bin/docs"

[output.html.search]
limit-results = 15
